### ISSUE TITLE
Use ipython 5's new paste functionality to fix long lines issue

### ISSUE THREAD

**Issue by alok** [jpalardy/vim-slime#123]
I figured I'd make this a separate issue. I'll quote the text I added to another issue:

> ipython 5 removed the %cpaste magic function and apparently just works with pasting long input directly. You may want to either add detection for ipython 5.x+, or require users to use it if they use  ipython (it has been out for months now). Then, you can use something other than `cpaste` (I'm not sure how they made it work, but it apparently does).

**Comment by jpalardy** [comment]
Hmmmm… does that just mean not turning on ipython mode? Or is there more to it?

**Comment by Alok** [comment]
I took a 200 line python script, copied it to the system clipboard, and then just hit Cmd-V to paste it and it pasted with the correct indentation. I'm not sure how they implement it. I'd try not turning it on and see if that works.

**Comment by aicherc** [comment]
I was able to get this to partially work by turning on "bracked paste mode" (https://cirw.in/blog/bracketed-paste), instead of using `%cpaste`. Specifically in `ftplugin/python/slime.vim` I changed
```
if exists('g:slime_python_ipython') && len(split(a:text,"\n")) > 1
   return ["%cpaste -q\n", a:text, "--\n"]
```
to 
```
if exists('g:slime_python_ipython') && len(split(a:text,"\n")) > 1
   return ["\e[200~", a:text, "\e[201~\n"]
```
where `\e[200~` and `\e[201~` are the bracketed paste escape sequences.
As far as I can tell, this prevents ipython 5.0+ from only reading the first line. 
See also (https://github.com/ipython/ipython/issues/9948)

I don't know enough about vimscript to make it check the current version of ipython (as multi-line pasting is version 5.0+).

**Comment by dlovell** [comment]
@jpalardy , "not turning on ipython mode" doesn't work because you need to [send something special](https://github.com/ipython/ipython/issues/9948#issuecomment-247745372) for "non-executing-newline"

> We need to bind a shortcut that adds a new line without executing, if you are scripting you can use C-o Down to force a newline and Escape Enter to force execution.

See also: [ENH: enable multiline send for ipython](https://github.com/dlovell/vim-slime/commit/60c7b7f4e28e6c415a50dffb2fbc4d442e2b6837)
(I think I like ["bracketed paste mode"](https://github.com/dlovell/vim-slime/commit/982de493cba335c86670e76b28aa12d10b87b1fa) better)

**Comment by jpalardy** [comment]
Based on what I'm reading, this is related to #142 ?

**Comment by NedWestern** [comment]
For IPython 7.2, I managed to get it working with the following changes:

    if exists('g:slime_python_ipython') && len(split(a:text,"\n")) > 1
      return ["%cpaste -q\n", g:slime_dispatch_ipython_pause, a:text, "--\n"]

to

    if exists('g:slime_python_ipython')
      return [a:text, g:slime_dispatch_ipython_pause, "\n"]

when vim-slime pastes the text, IPython 5.0+ will run the code with no problems, but it will not auto-execute. Adding the pause and the newline character makes IPython execute the code after pasting.

Note that for large blocks of code with empty lines, there is still a problem with IPython executing at *some* of these empty lines, which seems to occur randomly, indicating a timing issue. This will be a problem for indented code. I'm not sure how to address this.

**Comment by jpalardy** [comment]
I'll have to defer to an iPython user for a solution.

**Comment by NedWestern** [comment]
If I replace empty lines with a comment character, it suppresses early execution and somewhat preserves the layout of the code. A bit hacky, but it seems to work.

**Comment by NedWestern** [comment]
So... should I submit a pull request for testing perhaps? Or no?

**Comment by jpalardy** [comment]
I'm up for it.

If you send a PR, I'll merge it. If it doesn't work, we'll revert?

**Comment by NedWestern** [comment]
New to this... hopefully it's OK.

**Comment by aicherc** [comment]
@NedWestern 
For the problem with IPython executing at empty lines somewhat randomly (treating one code chunk as multiple chunks), have you tried adding the "bracketed paste mode" characters around `a.text`? (see https://github.com/jpalardy/vim-slime/issues/123#issuecomment-299616808)

I've been using it (for the last two years) to send code from vim to ipython using tmux and it's removed the issue of ipython thinking I'm sending multiple chunks (as far as I can tell).

Specifically replacing
```
if exists('g:slime_python_ipython')
  return [a:text, g:slime_dispatch_ipython_pause, "\n"]
```
with
```
if exists('g:slime_python_ipython')
  return ["\e[200~", a:text, "\e[201~", g:slime_dispatch_ipython_pause, "\n"]
```

It might let you avoid having to suppress empty lines with comment characters.

**Comment by NedWestern** [comment]
@aicherc 
Hi Christopher, yes I read your blog post. Sounds interesting, but I can not get it to work for my setup (IPython 7.2 in vimterminal in gVim). It sends the escape sequence, minus the "\e", and does not execute.

    In [1]: [200~print('foo')
            : ^[[201~
            :

Does it require specific settings in vim?

**Comment by aicherc** [comment]
@NedWestern 
Thanks for trying it out.  
After re-reading the blog post, it sounds like "bracketed paste mode" is only intended to work in terminals that support it (my setup is gnome-terminal + tmux). I'm not very familiar with vimterminal (or terminal emulation in vim/neovim) to know if they support it.

Based on this, I like your current solution (empty lines -> `#`), since it works more generally.

**Comment by NedWestern** [comment]
True, but it seems to break for some people... ugh.
