### ISSUE TITLE
Default SendSlime Key Mapping not Working

### ISSUE THREAD

**Issue by charleswm** [jpalardy/vim-slime#128]
Not sure if this is issue is on my end, but I can't get the default mapping of <C-c><C-c> to work. 

Everything works just fine if I use the manual commands with :SendSlime on a visually selected chunk of text. That being said, when I press C-c, C-c vim tells me "Type  :quit<Enter>  to exit Vim"

Any ideas on this?

I'm on OSX El Capitan, VIM8, tmux 2.3, using ITerm2 and Zsh.

**Comment by jpalardy** [comment]
Interesting, I haven't heard about this.

Have you tried different combinations? (maybe it's vim 8)

**Comment by jpalardy** [comment]
Old issue, re-open if needed.

**Comment by anmolkabra** [comment]
Default mappings don't work for me either. I'm on Ubuntu 18.04, tmux 2.6, vim 8.0. I get the same error and I have to use :SendSlime to send text. I'm trying to use OCaml with REPL [utop](https://github.com/diml/utop).

**Comment by jpalardy** [comment]
Does this only happen on `ctrl-c, ctrl-c`? What happens if you try another binding?

**Comment by againxx** [comment]
Having the same issue. When I start neovim, and use `<C-c><C-c>` to send paragraph, it works fine. But after a while, when I press `<C-c>`, it immediately shows the message "Type :qa and press <Enter> to exit Nvim". However, vim 8.2 works fine, and If I bind `<C-q>` instead of `<C-c>`, everything is ok.
It seems that the key binding of <C-c> in neovim is not consistent. My neovim version is 0.5.0.
Any suggestion?
