### ISSUE TITLE
SlimeConfig would fail if g:slime_target is modified in a session

### ISSUE THREAD

**Issue by randomizedthinking** [jpalardy/vim-slime#149]
My default target is: `tmux`. Occasionally, I would like to direct texts to neovim terminals. What I found is if the vim-slime function was used, then switch slime target manually would cause problems.

    :let g:slime_target = "neovim"

Likewise, if the vim-slime function is used once under `neovim` target, then switching to `tmux` would fail.

**Comment by jpalardy** [comment]
Hi there,

I think the problem has to do with the content of the `b:slime_config` variable. Since it contains `slime_target` -specific values (tmux uses `socket_name`, `target_pane` while neovim uses `jobid`), this will cause problem when trying to use the other config. (ie. `jobid` is missing)

The quick and dirty way out of this mess would be to

    :unlet b:slime_config

if you change the `g:slime_target` value. Let me know if that works.

**Comment by randomizedthinking** [comment]
Yes, it works. Thanks.

I think a good solution is to allow users to reconfigure vim-slime after reset `g:slime_target`. As of now, the reconfiguration would fail since the current implementation does not check the existence of right keys in `b:slime_config`. It seems not so hard to add some codes to guard missing keys in each `s:XXXXConfig` function. How do you think?

**Comment by jpalardy** [comment]
The reasons are mostly historical.

At first, there was only screen. Tmux came later … then others. As features piled onto the previous ones,  there was no _master plan_.

Looking through the code, it seemed like an obvious oversight to only check for the existence of the variable and not its content… On the other hand, I'm not sure there _was_ a use-case to support multiple multiplexers until now: people use screen _or_ tmux, or something else, but usually not in combination.

If the plugin were written in anything else, there is much I would like to improve. But vimscript is vimscript and I'm not sure the benefits of a rewrite would outweigh the possible incompatibilities it would bring.

Since there's a workaround, I'll go ahead and close this. But if you're willing to beef up the `b:slime_config` logic, I would consider that PR.

**Comment by randomizedthinking** [comment]
Just create a PR https://github.com/jpalardy/vim-slime/pull/150... let me know how you think.
