### ISSUE TITLE
(Neovim) Can't send raw data to rpc channel

### ISSUE THREAD

**Issue by a-elhag** [jpalardy/vim-slime#251]
I believe another [user](https://github.com/jpalardy/vim-slime/issues/212) had the same problem, but I do not know how they fixed it. I have just set up vim-slime in neovim and it is giving me an error of "can't send raw data to rpc channel" when I use the default shortcut(Control -C -C). It also asks me to set up jobid the first time I press the shortcut and automatically puts the number of 3 there. After that, this error just continues to show

![image](https://user-images.githubusercontent.com/48454648/85835501-2c3c0e00-b763-11ea-9484-7a7abcfc62e5.png)

**Comment by jpalardy** [comment]
cc: @z-huabao

Hi @albaraa-elhag,

I don't personally use the neovim terminal mode. But if you're willing to debug this, I'll help.

Let me know.

**Comment by albaraa-elhag** [comment]
Yeah, I'm willing to debug this. What do you need?

**Comment by jpalardy** [comment]
I would recommend you pepper the plugin code with `echom` to debug ([details](https://learnvimscriptthehardway.stevelosh.com/chapters/01.html)).

Take it step by step and see where things go wrong?

(as for details, you might have to refer to neovim's documentation, etc)

**Comment by ejolson9** [comment]
If anyone else has this issue,  it is likely because you need to manually specify the :terminal windows' job-id ( :echo b:terminal_job_id )  and pass it to the "jobid: " prompt that will come up with :SlimeConfig  .  The default value (3 for me) did not match the new :terminal window job-id.

A potential improvement would be to automatically look for a :term//  buffer,  and if there is only one,  use its job-id as default prompt value.  Or maybe just an additional line in the help docs, after the part about ':echo b:terminal_job_id' , that the user should pass this value to the :SlimeConfig prompt.  It seems obvious in retrospect, but will trip some people (like me) up.

**Comment by jpalardy** [comment]
Hi @ejolson9,

Good catch 😃 

When the vim-terminal patch came in, I was a bit surprised by the hardcoded `3`, but since I don't use vim-terminal, I wasn't sure how to make this better.

If you're willing to look into it, I would gratefully merge in improvements you come up with.

**Comment by kujbika** [comment]
I also face this issue.

**Comment by AkechiShiro** [comment]
Facing this issue as well.

**Comment by jpalardy** [comment]
@kujbika @AkechiShiro you can look at #263

**Comment by jpalardy** [comment]
closed by #266, re-open the issue if that code doesn't work for you
