### ISSUE TITLE
Issue #23 returns

### ISSUE THREAD

**Issue by markjreed** [jpalardy/vim-slime#406]
The "Slurped X characters into buffer" is back.  I don't see anything in the code to set `msgwait` to 0, as mentioned in #23.  Regression? It's painful to use without setting that parameter, but I don't want it in my screenrc because I usually want time to actually see the messages when using it interactively...

**Comment by jpalardy** [comment]
Hi @markjreed 

Following the trail, it certainly seems like we lost track of the initial problem
- 10d24f04003c606f8559039ca71ec881849af3d8 removed `msgwait` with `colon`
- ca062f4c19a89ab402c5ffa390c7f13f8994f828 removed `colon` logic, because I didn't see it happen when testing locally

Please open a PR with the fix — and a comment for how/when it happens — and it would be my pleasure to merge it.

Alternatively, if you can explain how recreate the problem, I can take care of it.
