### ISSUE TITLE
made three pull requests

### ISSUE THREAD

**Issue by jam1015** [jpalardy/vim-slime#442]
I've made three separate pull requests , each for its own feature.  They are #439  , #440  and #441 .

If its easier for you if I merge these all together into a single pull request I can do that.

**Comment by jpalardy** [comment]
Hi @jam1015 

I had no problem with #439, since it fell under the neovim plugin

As for #440 and #441 — we're right in the core, and in the tmux plugin -- so I'm having a harder time bringing them in 🤔 

Personally, I've been wanting to do _less_ in the core, not more. Same thing for the plugins. If there's a way to let people plug their own customizations (configuration comes to mind), that would be preferable to adding more features to slime itself.

**Comment by jam1015** [comment]
Ok I understand trying to keep things simple. I'll try to code up a way to let users make further customizations , and then suggesr the functionality I add in the wiki.

The changes to the commentation for the tmux target is verbose but I do want to explicitly note the tab completion that is already a feature. I'll open a smaller PR for that tomorrow.
